package pl.qprogramming.devinbox.audit.domain;

public enum AuditEventType {
    USER_CREATED,
    USER_AUTHENTICATED,
    AUTHENTICATION_FAILED,
    USER_LOGGED_OUT,
    SESSION_EXPIRED,
    GITHUB_CREDENTIAL_UPDATED,
    ADO_CREDENTIAL_UPDATED,
    USER_SETTINGS_UPDATED,
    MANUAL_SYNC_TRIGGERED,
    APPLICATION_STARTED
}
